#!/bin/bash

cat ./0600_Trafficspeed_Reduced | cut -f 1,3 -d ',' | sort > joinedFlow.txt

files=$(find -type f | sort | grep -v '0600' | grep '_Reduced')

for file in $files; do 
	printf '\rAdding %s to file' "$file"
	join -t ',' -j 1 joinedFlow.txt <(cat $file | cut -f 1,3 -d ',' | sort) > temp.txt
	cp temp.txt joinedFlow.txt
done
printf '\nDone! joinedFlow.txt created\n'

rm temp.txt
