#!/bin/bash

cat ./0600_Trafficspeed_Reduced | cut -f 1,2 -d ',' | sort > joinedSpeed.txt

files=$(find -type f | sort | grep -v '0600' | grep '_Reduced')

for file in $files; do 
	printf '\rAdding %s to file' "$file"
	join -t ',' -j 1 joinedSpeed.txt <(cat $file | cut -f 1,2 -d ',' | sort) > temp.txt
	cp temp.txt joinedSpeed.txt
done
printf '\nDone! joinedSpeed.txt created\n'

rm temp.txt
